spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnDevALX/ums-env
  application:
    name: ums-config-server
server:
  port: 9999

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

